#!/usr/bin/env python3
"""Generate reduced_log_table.h: mantissa thresholds for the log-power code.

round(log2(m) * 256) for m in [1, 2) equals the number of thresholds
2 ** ((k + 0.5) / 256), k = 0..255, that are <= m. The firmware counts them
by binary search, so it needs no libm. tests/test_iwr6843_reduced_firmware.py
checks the committed header matches this output.
"""

from __future__ import annotations

import sys
from pathlib import Path

STEPS = 256
HEADER = Path(__file__).with_name("reduced_log_table.h")


def render() -> str:
    values = [repr(2.0 ** ((k + 0.5) / STEPS)) for k in range(STEPS)]
    rows = [", ".join(values[i : i + 3]) for i in range(0, STEPS, 3)]
    body = ",\n    ".join(rows)
    return (
        "/* Generated by gen_reduced_log_table.py -- do not edit. */\n"
        "#ifndef REDUCED_LOG_TABLE_H\n"
        "#define REDUCED_LOG_TABLE_H\n\n"
        f"#define RO_LOG_TABLE_SIZE {STEPS}U\n\n"
        "/* 2 ** ((k + 0.5) / 256): rounding thresholds of 256 * log2(m), m in [1, 2). */\n"
        f"static const double ro_log_thresholds[RO_LOG_TABLE_SIZE] = {{\n    {body}\n}};\n\n"
        "#endif /* REDUCED_LOG_TABLE_H */\n"
    )


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "--check":
        sys.exit(0 if HEADER.read_text(encoding="utf-8") == render() else 1)
    HEADER.write_text(render(), encoding="utf-8")
